services:
  app:
    image: node:24-alpine
    container_name: recipe-search-app-frontend
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    expose:
      - "8004"
    command: sh -c "npm install && npm run dev -- --host --port 8004"
    stdin_open: true
    tty: true
    networks:
      - default
      - shared-gateway-net
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: recipe-search-app-backend
    volumes:
      - ./backend:/app
    expose:
      - "8005"
    environment:
      - PORT=8005
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - postgres
    networks:
      - default
      - shared-gateway-net
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: recipe-search-app-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - default
    restart: unless-stopped

volumes:
  db_data:


networks:
  shared-gateway-net:
    external: true
