services:
  app:
    image: node:24-alpine
    container_name: recipe-search-app-frontend
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    expose:
      - "8004"
    command: npm run dev -- --host --port 8004
    stdin_open: true
    tty: true
    networks:
      - default
      - shared-gateway-net
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: recipe-search-app-backend
    volumes:
      - ./backend:/app
    expose:
      - "8005"
    environment:
      - PORT=8005
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    #depends_on:
    #  - db
    networks:
      - default
      - shared-gateway-net
    restart: unless-stopped

#  db:
#    image: mysql:8.0
#    container_name: db
#    environment:
#      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#      - MYSQL_DATABASE=${MYSQL_DATABASE}
#      - MYSQL_USER=${MYSQL_USER}
#      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#    volumes:
#      - db_data:/var/lib/mysql
#    restart: unless-stopped

volumes:
  db_data:


networks:
  shared-gateway-net:
    external: true
